#cloud-config
groups:
  - ubuntu: [root,sys]

users:
  - default
  - name: asyncapi
    gecos: AsyncAPI
    primary-group: ubuntu
    groups: users, admin
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys: 
      - # Add your public key here
runcmd:
  - sudo apt-get update -y
  - sudo apt install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  - sudo apt-get update -y
  - sudo apt install docker-ce -y
  - sudo systemctl status docker
  - sudo usermod -aG docker ${USER}
  - sudo systemctl enable docker
  - sudo systemctl start docker
