name: Deploy to DigitalOcean Droplets

on:
  push:
    branches:
      - master
  
  workflow_dispatch: 
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'

jobs:
  deploy-app:
    name: Deploy to DigitalOcean App
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean App
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: "server-api"
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
